# uses amazon managed build env 2.0
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo installng docker phase ...........
      - mkdir /root/.npm-global
      - export PATH=/root/.npm-global/bin:$PATH
      - export NPM_CONFIG_PREFIX=/root/.npm-global
      - echo prefix ${NPM_CONFIG_PREFIX}
      - npm install -g gulp
      - npm install -g node-sass --unsafe-perm
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests -Preact
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
artifacts:
    files:
        - '**/*'
    base-directory: 'public_html*'
    discard-paths: yes
